# coding: utf-8

# flake8: noqa

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.14"

# Define package exports
__all__ = [
    "ChatApi",
    "EmbeddingsApi",
    "ModelsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ApiAPIError",
    "ApiChatCompletionRequest",
    "ApiChatCompletionResponse",
    "ApiChatMessage",
    "ApiChoice",
    "ApiErrorResponse",
    "ApiLeartechExt",
    "ApiModel",
    "ApiModelsResponse",
    "ApiUsage",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from leartech_ai_gateway.api.chat_api import ChatApi as ChatApi
    from leartech_ai_gateway.api.embeddings_api import EmbeddingsApi as EmbeddingsApi
    from leartech_ai_gateway.api.models_api import ModelsApi as ModelsApi
    
    # import ApiClient
    from leartech_ai_gateway.api_response import ApiResponse as ApiResponse
    from leartech_ai_gateway.api_client import ApiClient as ApiClient
    from leartech_ai_gateway.configuration import Configuration as Configuration
    from leartech_ai_gateway.exceptions import OpenApiException as OpenApiException
    from leartech_ai_gateway.exceptions import ApiTypeError as ApiTypeError
    from leartech_ai_gateway.exceptions import ApiValueError as ApiValueError
    from leartech_ai_gateway.exceptions import ApiKeyError as ApiKeyError
    from leartech_ai_gateway.exceptions import ApiAttributeError as ApiAttributeError
    from leartech_ai_gateway.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from leartech_ai_gateway.models.api_api_error import ApiAPIError as ApiAPIError
    from leartech_ai_gateway.models.api_chat_completion_request import ApiChatCompletionRequest as ApiChatCompletionRequest
    from leartech_ai_gateway.models.api_chat_completion_response import ApiChatCompletionResponse as ApiChatCompletionResponse
    from leartech_ai_gateway.models.api_chat_message import ApiChatMessage as ApiChatMessage
    from leartech_ai_gateway.models.api_choice import ApiChoice as ApiChoice
    from leartech_ai_gateway.models.api_error_response import ApiErrorResponse as ApiErrorResponse
    from leartech_ai_gateway.models.api_leartech_ext import ApiLeartechExt as ApiLeartechExt
    from leartech_ai_gateway.models.api_model import ApiModel as ApiModel
    from leartech_ai_gateway.models.api_models_response import ApiModelsResponse as ApiModelsResponse
    from leartech_ai_gateway.models.api_usage import ApiUsage as ApiUsage
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from leartech_ai_gateway.api.chat_api import ChatApi as ChatApi
from leartech_ai_gateway.api.embeddings_api import EmbeddingsApi as EmbeddingsApi
from leartech_ai_gateway.api.models_api import ModelsApi as ModelsApi

# import ApiClient
from leartech_ai_gateway.api_response import ApiResponse as ApiResponse
from leartech_ai_gateway.api_client import ApiClient as ApiClient
from leartech_ai_gateway.configuration import Configuration as Configuration
from leartech_ai_gateway.exceptions import OpenApiException as OpenApiException
from leartech_ai_gateway.exceptions import ApiTypeError as ApiTypeError
from leartech_ai_gateway.exceptions import ApiValueError as ApiValueError
from leartech_ai_gateway.exceptions import ApiKeyError as ApiKeyError
from leartech_ai_gateway.exceptions import ApiAttributeError as ApiAttributeError
from leartech_ai_gateway.exceptions import ApiException as ApiException

# import models into sdk package
from leartech_ai_gateway.models.api_api_error import ApiAPIError as ApiAPIError
from leartech_ai_gateway.models.api_chat_completion_request import ApiChatCompletionRequest as ApiChatCompletionRequest
from leartech_ai_gateway.models.api_chat_completion_response import ApiChatCompletionResponse as ApiChatCompletionResponse
from leartech_ai_gateway.models.api_chat_message import ApiChatMessage as ApiChatMessage
from leartech_ai_gateway.models.api_choice import ApiChoice as ApiChoice
from leartech_ai_gateway.models.api_error_response import ApiErrorResponse as ApiErrorResponse
from leartech_ai_gateway.models.api_leartech_ext import ApiLeartechExt as ApiLeartechExt
from leartech_ai_gateway.models.api_model import ApiModel as ApiModel
from leartech_ai_gateway.models.api_models_response import ApiModelsResponse as ApiModelsResponse
from leartech_ai_gateway.models.api_usage import ApiUsage as ApiUsage

""",
            name=__name__,
            doc=__doc__,
        )
    )
