# coding: utf-8

# flake8: noqa
"""
    Catalog MCP API

    Read-only inventory of leartech services for BA/Architect agents. Foundation for V6-P10 + the new-product layer.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from leartech_catalog_mcp.models.handlers_example_response import HandlersExampleResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from leartech_catalog_mcp.models.handlers_example_response import HandlersExampleResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
