# coding: utf-8

"""
    Leartech Plan Conformance Consumer API

    Reference Maestro CONSUMER service — accepts events on POST /consume_event, records them, exposes /confirmed + /events for test-runners to assert an event actually flowed end-to-end. Deployed into jx-plan-conformance and pointed at the isolated Maestro bus.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_plan_conformance_consumer.api.maestro_api import MaestroApi


class TestMaestroApi(unittest.IsolatedAsyncioTestCase):
    """MaestroApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MaestroApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_confirmed_get(self) -> None:
        """Test case for confirmed_get

        Check whether an event has been consumed
        """
        pass

    async def test_consume_event_post(self) -> None:
        """Test case for consume_event_post

        Maestro event consumer endpoint
        """
        pass

    async def test_events_get(self) -> None:
        """Test case for events_get

        Debug dump of all recorded events
        """
        pass


if __name__ == '__main__':
    unittest.main()
