# coding: utf-8

"""
    Leartech Plan Conformance Consumer API

    Reference Maestro CONSUMER service — accepts events on POST /consume_event, records them, exposes /confirmed + /events for test-runners to assert an event actually flowed end-to-end. Deployed into jx-plan-conformance and pointed at the isolated Maestro bus.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_plan_conformance_consumer.models.internal_handlers_fleet_test_response import InternalHandlersFleetTestResponse

class TestInternalHandlersFleetTestResponse(unittest.TestCase):
    """InternalHandlersFleetTestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InternalHandlersFleetTestResponse:
        """Test InternalHandlersFleetTestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InternalHandlersFleetTestResponse`
        """
        model = InternalHandlersFleetTestResponse()
        if include_optional:
            return InternalHandlersFleetTestResponse(
                results = [
                    leartech_plan_conformance_consumer.models.internal_handlers/peer_result.internal_handlers.peerResult(
                        duration_ms = 56, 
                        http_code = 56, 
                        message = '', 
                        ok = True, 
                        peer = '', )
                    ],
                success = True,
                summary = ''
            )
        else:
            return InternalHandlersFleetTestResponse(
        )
        """

    def testInternalHandlersFleetTestResponse(self):
        """Test InternalHandlersFleetTestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
