# coding: utf-8

"""
    leartech-lighthouse-pr-events API

    Lighthouse external plugin. Consumes GitHub PR webhooks relayed via util.ParseExternalPluginEvent and announces pr.merged / pr.closed_unmerged to Maestro.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_lighthouse_pr_events.api.webhook_api import WebhookApi


class TestWebhookApi(unittest.IsolatedAsyncioTestCase):
    """WebhookApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = WebhookApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_lighthouse_events_post(self) -> None:
        """Test case for lighthouse_events_post

        Lighthouse external-plugin webhook receiver
        """
        pass


if __name__ == '__main__':
    unittest.main()
