# coding: utf-8

# flake8: noqa
"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from leartech_maestro_service.models.announce_event_request import AnnounceEventRequest
    from leartech_maestro_service.models.announce_event_response import AnnounceEventResponse
    from leartech_maestro_service.models.consume_event_request import ConsumeEventRequest
    from leartech_maestro_service.models.consume_event_response import ConsumeEventResponse
    from leartech_maestro_service.models.consumer import Consumer
    from leartech_maestro_service.models.event_consumption_dto import EventConsumptionDto
    from leartech_maestro_service.models.event_dto import EventDto
    from leartech_maestro_service.models.event_registration_info import EventRegistrationInfo
    from leartech_maestro_service.models.get_event_registration_info_for_name_response import GetEventRegistrationInfoForNameResponse
    from leartech_maestro_service.models.get_event_registration_info_response import GetEventRegistrationInfoResponse
    from leartech_maestro_service.models.get_events_dto_response import GetEventsDtoResponse
    from leartech_maestro_service.models.get_latest_events_details_response import GetLatestEventsDetailsResponse
    from leartech_maestro_service.models.latest_event_dto import LatestEventDto
    from leartech_maestro_service.models.latest_failed_event_consumption_dto import LatestFailedEventConsumptionDto
    from leartech_maestro_service.models.latest_successful_event_consumption_dto import LatestSuccessfulEventConsumptionDto
    from leartech_maestro_service.models.producer import Producer
    from leartech_maestro_service.models.response import Response
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from leartech_maestro_service.models.announce_event_request import AnnounceEventRequest
from leartech_maestro_service.models.announce_event_response import AnnounceEventResponse
from leartech_maestro_service.models.consume_event_request import ConsumeEventRequest
from leartech_maestro_service.models.consume_event_response import ConsumeEventResponse
from leartech_maestro_service.models.consumer import Consumer
from leartech_maestro_service.models.event_consumption_dto import EventConsumptionDto
from leartech_maestro_service.models.event_dto import EventDto
from leartech_maestro_service.models.event_registration_info import EventRegistrationInfo
from leartech_maestro_service.models.get_event_registration_info_for_name_response import GetEventRegistrationInfoForNameResponse
from leartech_maestro_service.models.get_event_registration_info_response import GetEventRegistrationInfoResponse
from leartech_maestro_service.models.get_events_dto_response import GetEventsDtoResponse
from leartech_maestro_service.models.get_latest_events_details_response import GetLatestEventsDetailsResponse
from leartech_maestro_service.models.latest_event_dto import LatestEventDto
from leartech_maestro_service.models.latest_failed_event_consumption_dto import LatestFailedEventConsumptionDto
from leartech_maestro_service.models.latest_successful_event_consumption_dto import LatestSuccessfulEventConsumptionDto
from leartech_maestro_service.models.producer import Producer
from leartech_maestro_service.models.response import Response

""",
            name=__name__,
            doc=__doc__,
        )
    )
