# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from leartech_maestro_service.models.event_consumption_dto import EventConsumptionDto
from typing import Optional, Set
from typing_extensions import Self

class EventDto(BaseModel):
    """
    EventDto
    """ # noqa: E501
    actioned_by: Optional[StrictStr] = Field(default=None, alias="actionedBy")
    annotations: Optional[Dict[str, StrictStr]] = None
    consumptions: Optional[List[EventConsumptionDto]] = None
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    produced_by: Optional[StrictStr] = Field(default=None, alias="producedBy")
    produced_time: Optional[StrictStr] = Field(default=None, alias="producedTime")
    __properties: ClassVar[List[str]] = ["actionedBy", "annotations", "consumptions", "id", "name", "producedBy", "producedTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EventDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in consumptions (list)
        _items = []
        if self.consumptions:
            for _item_consumptions in self.consumptions:
                if _item_consumptions:
                    _items.append(_item_consumptions.to_dict())
            _dict['consumptions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EventDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actionedBy": obj.get("actionedBy"),
            "annotations": obj.get("annotations"),
            "consumptions": [EventConsumptionDto.from_dict(_item) for _item in obj["consumptions"]] if obj.get("consumptions") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "producedBy": obj.get("producedBy"),
            "producedTime": obj.get("producedTime")
        })
        return _obj


