# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from leartech_maestro_service.models.latest_event_dto import LatestEventDto
from typing import Optional, Set
from typing_extensions import Self

class GetLatestEventsDetailsResponse(BaseModel):
    """
    GetLatestEventsDetailsResponse
    """ # noqa: E501
    error_description: Optional[StrictStr] = Field(default=None, alias="errorDescription")
    latest_events: Optional[List[LatestEventDto]] = Field(default=None, alias="latestEvents")
    success: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["errorDescription", "latestEvents", "success"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetLatestEventsDetailsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in latest_events (list)
        _items = []
        if self.latest_events:
            for _item_latest_events in self.latest_events:
                if _item_latest_events:
                    _items.append(_item_latest_events.to_dict())
            _dict['latestEvents'] = _items
        # set to None if error_description (nullable) is None
        # and model_fields_set contains the field
        if self.error_description is None and "error_description" in self.model_fields_set:
            _dict['errorDescription'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetLatestEventsDetailsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "errorDescription": obj.get("errorDescription"),
            "latestEvents": [LatestEventDto.from_dict(_item) for _item in obj["latestEvents"]] if obj.get("latestEvents") is not None else None,
            "success": obj.get("success")
        })
        return _obj


