# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from leartech_maestro_service.models.latest_failed_event_consumption_dto import LatestFailedEventConsumptionDto
from leartech_maestro_service.models.latest_successful_event_consumption_dto import LatestSuccessfulEventConsumptionDto
from typing import Optional, Set
from typing_extensions import Self

class LatestEventDto(BaseModel):
    """
    LatestEventDto
    """ # noqa: E501
    latest_failed_consumptions: Optional[List[LatestFailedEventConsumptionDto]] = Field(default=None, alias="latestFailedConsumptions")
    latest_successful_consumptions: Optional[List[LatestSuccessfulEventConsumptionDto]] = Field(default=None, alias="latestSuccessfulConsumptions")
    name: Optional[StrictStr] = None
    produced_by: Optional[StrictStr] = Field(default=None, alias="producedBy")
    produced_time: Optional[StrictStr] = Field(default=None, alias="producedTime")
    __properties: ClassVar[List[str]] = ["latestFailedConsumptions", "latestSuccessfulConsumptions", "name", "producedBy", "producedTime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LatestEventDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in latest_failed_consumptions (list)
        _items = []
        if self.latest_failed_consumptions:
            for _item_latest_failed_consumptions in self.latest_failed_consumptions:
                if _item_latest_failed_consumptions:
                    _items.append(_item_latest_failed_consumptions.to_dict())
            _dict['latestFailedConsumptions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in latest_successful_consumptions (list)
        _items = []
        if self.latest_successful_consumptions:
            for _item_latest_successful_consumptions in self.latest_successful_consumptions:
                if _item_latest_successful_consumptions:
                    _items.append(_item_latest_successful_consumptions.to_dict())
            _dict['latestSuccessfulConsumptions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LatestEventDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "latestFailedConsumptions": [LatestFailedEventConsumptionDto.from_dict(_item) for _item in obj["latestFailedConsumptions"]] if obj.get("latestFailedConsumptions") is not None else None,
            "latestSuccessfulConsumptions": [LatestSuccessfulEventConsumptionDto.from_dict(_item) for _item in obj["latestSuccessfulConsumptions"]] if obj.get("latestSuccessfulConsumptions") is not None else None,
            "name": obj.get("name"),
            "producedBy": obj.get("producedBy"),
            "producedTime": obj.get("producedTime")
        })
        return _obj


