# coding: utf-8

"""
    Leartech Go Service Template API

    Golden Go service template — replace this description after cloning.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ba_service.models.handlers_clients_response import HandlersClientsResponse

class TestHandlersClientsResponse(unittest.TestCase):
    """HandlersClientsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersClientsResponse:
        """Test HandlersClientsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersClientsResponse`
        """
        model = HandlersClientsResponse()
        if include_optional:
            return HandlersClientsResponse(
                checksums_url = '',
                clients = [
                    leartech_ba_service.models.handlers/client_binary.handlers.ClientBinary(
                        arch = '', 
                        bytes = 56, 
                        name = '', 
                        os = '', 
                        sha256 = '', 
                        url = '', )
                    ],
                version = ''
            )
        else:
            return HandlersClientsResponse(
        )
        """

    def testHandlersClientsResponse(self):
        """Test HandlersClientsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
