# coding: utf-8

"""
    Leartech Go Service Template API

    Golden Go service template — replace this description after cloning.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ba_service.api.shell_api import ShellApi


class TestShellApi(unittest.IsolatedAsyncioTestCase):
    """ShellApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ShellApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_shell_prompt_get(self) -> None:
        """Test case for api_v1_shell_prompt_get

        The system prompt for the terminal client
        """
        pass


if __name__ == '__main__':
    unittest.main()
