# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ai_gateway.models.api_models_response import ApiModelsResponse

class TestApiModelsResponse(unittest.TestCase):
    """ApiModelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiModelsResponse:
        """Test ApiModelsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiModelsResponse`
        """
        model = ApiModelsResponse()
        if include_optional:
            return ApiModelsResponse(
                data = [
                    leartech_ai_gateway.models.api/model.api.Model(
                        id = '', 
                        object = '', 
                        owned_by = '', )
                    ],
                object = ''
            )
        else:
            return ApiModelsResponse(
        )
        """

    def testApiModelsResponse(self):
        """Test ApiModelsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
