# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ai_gateway.api.meta_api import MetaApi


class TestMetaApi(unittest.IsolatedAsyncioTestCase):
    """MetaApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MetaApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_version_get(self) -> None:
        """Test case for version_get

        Gateway version and wire-contract level
        """
        pass


if __name__ == '__main__':
    unittest.main()
