# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ai_gateway.models.api_chat_completion_response import ApiChatCompletionResponse

class TestApiChatCompletionResponse(unittest.TestCase):
    """ApiChatCompletionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiChatCompletionResponse:
        """Test ApiChatCompletionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiChatCompletionResponse`
        """
        model = ApiChatCompletionResponse()
        if include_optional:
            return ApiChatCompletionResponse(
                choices = [
                    leartech_ai_gateway.models.api/choice.api.Choice(
                        finish_reason = '', 
                        index = 56, 
                        message = leartech_ai_gateway.models.api/chat_message.api.ChatMessage(
                            content = '', 
                            role = '', ), )
                    ],
                created = 56,
                id = '',
                model = '',
                object = '',
                usage = leartech_ai_gateway.models.api/usage.api.Usage(
                    completion_tokens = 56, 
                    prompt_tokens = 56, 
                    total_tokens = 56, )
            )
        else:
            return ApiChatCompletionResponse(
        )
        """

    def testApiChatCompletionResponse(self):
        """Test ApiChatCompletionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
