# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ai_gateway.models.api_list_keys_response import ApiListKeysResponse

class TestApiListKeysResponse(unittest.TestCase):
    """ApiListKeysResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiListKeysResponse:
        """Test ApiListKeysResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiListKeysResponse`
        """
        model = ApiListKeysResponse()
        if include_optional:
            return ApiListKeysResponse(
                keys = [
                    leartech_ai_gateway.models.api/key_view.api.keyView(
                        budget_micros = 56, 
                        created_at = '', 
                        created_by = '', 
                        expires_at = '', 
                        keyid = '', 
                        last_used_at = '', 
                        model_allowlist = [
                            ''
                            ], 
                        name = '', 
                        rate_limit_rpm = 56, 
                        revoked_at = '', 
                        scopes = [
                            ''
                            ], )
                    ]
            )
        else:
            return ApiListKeysResponse(
        )
        """

    def testApiListKeysResponse(self):
        """Test ApiListKeysResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
