# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ai_gateway.models.websearch_item import WebsearchItem

class TestWebsearchItem(unittest.TestCase):
    """WebsearchItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebsearchItem:
        """Test WebsearchItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebsearchItem`
        """
        model = WebsearchItem()
        if include_optional:
            return WebsearchItem(
                content = '',
                score = 1.337,
                title = '',
                url = ''
            )
        else:
            return WebsearchItem(
        )
        """

    def testWebsearchItem(self):
        """Test WebsearchItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
