# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_ai_gateway.models.api_prompt_tokens_details import ApiPromptTokensDetails

class TestApiPromptTokensDetails(unittest.TestCase):
    """ApiPromptTokensDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiPromptTokensDetails:
        """Test ApiPromptTokensDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiPromptTokensDetails`
        """
        model = ApiPromptTokensDetails()
        if include_optional:
            return ApiPromptTokensDetails(
                cached_tokens = 56
            )
        else:
            return ApiPromptTokensDetails(
        )
        """

    def testApiPromptTokensDetails(self):
        """Test ApiPromptTokensDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
