# coding: utf-8

"""
    Leartech Go Service Template API

    Golden Go service template — replace this description after cloning.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HandlersShellPrompt(BaseModel):
    """
    HandlersShellPrompt
    """ # noqa: E501
    label: Optional[StrictStr] = Field(default=None, description="Label is the human name for this prompt, if the cluster set one. Free text for a reader; Revision is what identifies it.")
    prompt: Optional[StrictStr] = Field(default=None, description="Prompt is the system prompt, or empty when this cluster sets none.")
    revision: Optional[StrictStr] = Field(default=None, description="Revision identifies this exact text.  A content hash, not a hand-set number. // proven-by: TestShellPrompt_RevisionIsDerivedFromTheContent A version someone has to remember to bump goes stale quietly, and two different prompts claiming one revision make every session recorded against it unreadable. Derived from the bytes, so it agrees with what was served.  proven-by: TestShellPrompt_RevisionIsDerivedFromTheContent proven-by: TestShellPrompt_DifferentPromptsNeverShareARevision")
    source: Optional[StrictStr] = Field(default=None, description="Source names where the value came from, for a client that has to tell an operator which prompt it is running.")
    __properties: ClassVar[List[str]] = ["label", "prompt", "revision", "source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HandlersShellPrompt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HandlersShellPrompt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "label": obj.get("label"),
            "prompt": obj.get("prompt"),
            "revision": obj.get("revision"),
            "source": obj.get("source")
        })
        return _obj


