# coding: utf-8

# flake8: noqa

"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.73"

# Define package exports
__all__ = [
    "AdminApi",
    "DCRApi",
    "LoginApi",
    "TwoFactorApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ModelsAdminCreateTenantRequest",
    "ModelsAdminSetPermissionsRequest",
    "ModelsAdminSetRoleRequest",
    "ModelsAuthResponse",
    "ModelsDCRError",
    "ModelsDCRRegisterRequest",
    "ModelsDCRRegisterResponse",
    "ModelsLoginRequest",
    "ModelsTenant",
    "ModelsTwoFactorEnableResponse",
    "ModelsTwoFactorSubmitRequest",
    "ModelsUser",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from leartech_auth_service.api.admin_api import AdminApi as AdminApi
    from leartech_auth_service.api.dcr_api import DCRApi as DCRApi
    from leartech_auth_service.api.login_api import LoginApi as LoginApi
    from leartech_auth_service.api.two_factor_api import TwoFactorApi as TwoFactorApi
    from leartech_auth_service.api.user_api import UserApi as UserApi
    
    # import ApiClient
    from leartech_auth_service.api_response import ApiResponse as ApiResponse
    from leartech_auth_service.api_client import ApiClient as ApiClient
    from leartech_auth_service.configuration import Configuration as Configuration
    from leartech_auth_service.exceptions import OpenApiException as OpenApiException
    from leartech_auth_service.exceptions import ApiTypeError as ApiTypeError
    from leartech_auth_service.exceptions import ApiValueError as ApiValueError
    from leartech_auth_service.exceptions import ApiKeyError as ApiKeyError
    from leartech_auth_service.exceptions import ApiAttributeError as ApiAttributeError
    from leartech_auth_service.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from leartech_auth_service.models.models_admin_create_tenant_request import ModelsAdminCreateTenantRequest as ModelsAdminCreateTenantRequest
    from leartech_auth_service.models.models_admin_set_permissions_request import ModelsAdminSetPermissionsRequest as ModelsAdminSetPermissionsRequest
    from leartech_auth_service.models.models_admin_set_role_request import ModelsAdminSetRoleRequest as ModelsAdminSetRoleRequest
    from leartech_auth_service.models.models_auth_response import ModelsAuthResponse as ModelsAuthResponse
    from leartech_auth_service.models.models_dcr_error import ModelsDCRError as ModelsDCRError
    from leartech_auth_service.models.models_dcr_register_request import ModelsDCRRegisterRequest as ModelsDCRRegisterRequest
    from leartech_auth_service.models.models_dcr_register_response import ModelsDCRRegisterResponse as ModelsDCRRegisterResponse
    from leartech_auth_service.models.models_login_request import ModelsLoginRequest as ModelsLoginRequest
    from leartech_auth_service.models.models_tenant import ModelsTenant as ModelsTenant
    from leartech_auth_service.models.models_two_factor_enable_response import ModelsTwoFactorEnableResponse as ModelsTwoFactorEnableResponse
    from leartech_auth_service.models.models_two_factor_submit_request import ModelsTwoFactorSubmitRequest as ModelsTwoFactorSubmitRequest
    from leartech_auth_service.models.models_user import ModelsUser as ModelsUser
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from leartech_auth_service.api.admin_api import AdminApi as AdminApi
from leartech_auth_service.api.dcr_api import DCRApi as DCRApi
from leartech_auth_service.api.login_api import LoginApi as LoginApi
from leartech_auth_service.api.two_factor_api import TwoFactorApi as TwoFactorApi
from leartech_auth_service.api.user_api import UserApi as UserApi

# import ApiClient
from leartech_auth_service.api_response import ApiResponse as ApiResponse
from leartech_auth_service.api_client import ApiClient as ApiClient
from leartech_auth_service.configuration import Configuration as Configuration
from leartech_auth_service.exceptions import OpenApiException as OpenApiException
from leartech_auth_service.exceptions import ApiTypeError as ApiTypeError
from leartech_auth_service.exceptions import ApiValueError as ApiValueError
from leartech_auth_service.exceptions import ApiKeyError as ApiKeyError
from leartech_auth_service.exceptions import ApiAttributeError as ApiAttributeError
from leartech_auth_service.exceptions import ApiException as ApiException

# import models into sdk package
from leartech_auth_service.models.models_admin_create_tenant_request import ModelsAdminCreateTenantRequest as ModelsAdminCreateTenantRequest
from leartech_auth_service.models.models_admin_set_permissions_request import ModelsAdminSetPermissionsRequest as ModelsAdminSetPermissionsRequest
from leartech_auth_service.models.models_admin_set_role_request import ModelsAdminSetRoleRequest as ModelsAdminSetRoleRequest
from leartech_auth_service.models.models_auth_response import ModelsAuthResponse as ModelsAuthResponse
from leartech_auth_service.models.models_dcr_error import ModelsDCRError as ModelsDCRError
from leartech_auth_service.models.models_dcr_register_request import ModelsDCRRegisterRequest as ModelsDCRRegisterRequest
from leartech_auth_service.models.models_dcr_register_response import ModelsDCRRegisterResponse as ModelsDCRRegisterResponse
from leartech_auth_service.models.models_login_request import ModelsLoginRequest as ModelsLoginRequest
from leartech_auth_service.models.models_tenant import ModelsTenant as ModelsTenant
from leartech_auth_service.models.models_two_factor_enable_response import ModelsTwoFactorEnableResponse as ModelsTwoFactorEnableResponse
from leartech_auth_service.models.models_two_factor_submit_request import ModelsTwoFactorSubmitRequest as ModelsTwoFactorSubmitRequest
from leartech_auth_service.models.models_user import ModelsUser as ModelsUser

""",
            name=__name__,
            doc=__doc__,
        )
    )
