# coding: utf-8

"""
    Leartech Mortgages API

    Mortgages-domain BFF / orchestrator. REST + OpenAPI; sourcing comparison, indicative affordability, total-cost calculation, saved sourcing sessions, minimal case header. Consumed by leartech-mortgages-gw and any future SPA/mobile/partner client via auto-generated SDKs.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_mortgages_api.api.health_api import HealthApi


class TestHealthApi(unittest.IsolatedAsyncioTestCase):
    """HealthApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = HealthApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_health_live_get(self) -> None:
        """Test case for health_live_get

        Liveness probe
        """
        pass

    async def test_health_ready_get(self) -> None:
        """Test case for health_ready_get

        Readiness probe
        """
        pass


if __name__ == '__main__':
    unittest.main()
