# coding: utf-8

"""
    Leartech Mortgages API

    Mortgages-domain BFF / orchestrator. REST + OpenAPI; sourcing comparison, indicative affordability, total-cost calculation, saved sourcing sessions, minimal case header. Consumed by leartech-mortgages-gw and any future SPA/mobile/partner client via auto-generated SDKs.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_mortgages_api.api.fleet_test_api import FleetTestApi


class TestFleetTestApi(unittest.IsolatedAsyncioTestCase):
    """FleetTestApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FleetTestApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_api_v1_fleet_test_get(self) -> None:
        """Test case for api_v1_fleet_test_get

        Fleet test endpoint — calls peer template SDKs to prove cross-service auth + SDK wiring.
        """
        pass


if __name__ == '__main__':
    unittest.main()
