# coding: utf-8

# flake8: noqa
"""
    leartech-lighthouse-pr-events API

    Leartech Lighthouse PR-events service. Scaffolded from leartech-go-service-template.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from leartech_lighthouse_pr_events.models.handlers_example_response import HandlersExampleResponse
    from leartech_lighthouse_pr_events.models.handlers_fleet_test_response import HandlersFleetTestResponse
    from leartech_lighthouse_pr_events.models.handlers_peer_result import HandlersPeerResult
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from leartech_lighthouse_pr_events.models.handlers_example_response import HandlersExampleResponse
from leartech_lighthouse_pr_events.models.handlers_fleet_test_response import HandlersFleetTestResponse
from leartech_lighthouse_pr_events.models.handlers_peer_result import HandlersPeerResult

""",
            name=__name__,
            doc=__doc__,
        )
    )
