# coding: utf-8

# flake8: noqa
"""
    leartech-lighthouse-pr-events API

    Lighthouse external plugin. Consumes GitHub PR webhooks relayed via util.ParseExternalPluginEvent and announces pr.merged / pr.closed_unmerged to Maestro.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package

""",
            name=__name__,
            doc=__doc__,
        )
    )
