# coding: utf-8

# flake8: noqa

"""
    webCoder BFF API

    Backend-for-frontend for the webCoder SaaS — agent orchestration, tenant provisioning, pipeline translation.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "AuthApi",
    "HealthApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HandlersMeResponse",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from webcoder_service.api.auth_api import AuthApi as AuthApi
    from webcoder_service.api.health_api import HealthApi as HealthApi
    
    # import ApiClient
    from webcoder_service.api_response import ApiResponse as ApiResponse
    from webcoder_service.api_client import ApiClient as ApiClient
    from webcoder_service.configuration import Configuration as Configuration
    from webcoder_service.exceptions import OpenApiException as OpenApiException
    from webcoder_service.exceptions import ApiTypeError as ApiTypeError
    from webcoder_service.exceptions import ApiValueError as ApiValueError
    from webcoder_service.exceptions import ApiKeyError as ApiKeyError
    from webcoder_service.exceptions import ApiAttributeError as ApiAttributeError
    from webcoder_service.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from webcoder_service.models.handlers_me_response import HandlersMeResponse as HandlersMeResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from webcoder_service.api.auth_api import AuthApi as AuthApi
from webcoder_service.api.health_api import HealthApi as HealthApi

# import ApiClient
from webcoder_service.api_response import ApiResponse as ApiResponse
from webcoder_service.api_client import ApiClient as ApiClient
from webcoder_service.configuration import Configuration as Configuration
from webcoder_service.exceptions import OpenApiException as OpenApiException
from webcoder_service.exceptions import ApiTypeError as ApiTypeError
from webcoder_service.exceptions import ApiValueError as ApiValueError
from webcoder_service.exceptions import ApiKeyError as ApiKeyError
from webcoder_service.exceptions import ApiAttributeError as ApiAttributeError
from webcoder_service.exceptions import ApiException as ApiException

# import models into sdk package
from webcoder_service.models.handlers_me_response import HandlersMeResponse as HandlersMeResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
