# coding: utf-8

"""
    webCoder BFF API

    Backend-for-frontend for the webCoder SaaS — agent orchestration, tenant provisioning, pipeline translation.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webcoder_service.models.handlers_initiative_assets import HandlersInitiativeAssets

class TestHandlersInitiativeAssets(unittest.TestCase):
    """HandlersInitiativeAssets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersInitiativeAssets:
        """Test HandlersInitiativeAssets
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersInitiativeAssets`
        """
        model = HandlersInitiativeAssets()
        if include_optional:
            return HandlersInitiativeAssets(
                coverage = '',
                sticky_comment = '',
                trace = ''
            )
        else:
            return HandlersInitiativeAssets(
        )
        """

    def testHandlersInitiativeAssets(self):
        """Test HandlersInitiativeAssets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
