# coding: utf-8

"""
    webCoder BFF API

    Backend-for-frontend for the webCoder SaaS — agent orchestration, tenant provisioning, pipeline translation.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webcoder_service.models.handlers_me_response import HandlersMeResponse

class TestHandlersMeResponse(unittest.TestCase):
    """HandlersMeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersMeResponse:
        """Test HandlersMeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersMeResponse`
        """
        model = HandlersMeResponse()
        if include_optional:
            return HandlersMeResponse(
                permissions = [User],
                scopes = [openid, offline, user],
                user_id = 'test@leartech.com'
            )
        else:
            return HandlersMeResponse(
        )
        """

    def testHandlersMeResponse(self):
        """Test HandlersMeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
