# coding: utf-8

"""
    webCoder BFF API

    Backend-for-frontend for the webCoder SaaS — agent orchestration, tenant provisioning, pipeline translation.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webcoder_service.models.handlers_initiative_run import HandlersInitiativeRun

class TestHandlersInitiativeRun(unittest.TestCase):
    """HandlersInitiativeRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersInitiativeRun:
        """Test HandlersInitiativeRun
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersInitiativeRun`
        """
        model = HandlersInitiativeRun()
        if include_optional:
            return HandlersInitiativeRun(
                assets = webcoder_service.models.handlers/initiative_assets.handlers.InitiativeAssets(
                    coverage = '', 
                    sticky_comment = '', 
                    trace = '', ),
                budget_iter = 5,
                created_at = '2026-05-05T12:00:00Z',
                defer_reason = '',
                initiative = 'webcoder-ui-add-about-page',
                iteration = 2,
                last_update = '2026-05-05T12:05:00Z',
                project_id = 'a1f2...',
                run_id = 'agent-init-add-about-page-a1b2c3',
                source_pr = '123',
                state = 'running',
                target_pr = 'https://github.com/.../pull/456',
                tenant = 'acme',
                triggered_by = 'alice@acme.com'
            )
        else:
            return HandlersInitiativeRun(
        )
        """

    def testHandlersInitiativeRun(self):
        """Test HandlersInitiativeRun"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
