# coding: utf-8

"""
    webCoder BFF API

    Backend-for-frontend for the webCoder SaaS — agent orchestration, tenant provisioning, pipeline translation.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from webcoder_service.models.handlers_create_initiative_response import HandlersCreateInitiativeResponse

class TestHandlersCreateInitiativeResponse(unittest.TestCase):
    """HandlersCreateInitiativeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersCreateInitiativeResponse:
        """Test HandlersCreateInitiativeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersCreateInitiativeResponse`
        """
        model = HandlersCreateInitiativeResponse()
        if include_optional:
            return HandlersCreateInitiativeResponse(
                logs = '/api/v1/initiatives/agent-init-add-about-page-a1b2c3/logs',
                run_id = 'agent-init-add-about-page-a1b2c3',
                var_self = '/api/v1/initiatives/agent-init-add-about-page-a1b2c3',
                state = 'queued'
            )
        else:
            return HandlersCreateInitiativeResponse(
        )
        """

    def testHandlersCreateInitiativeResponse(self):
        """Test HandlersCreateInitiativeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
