# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.models.latest_failed_event_consumption_dto import LatestFailedEventConsumptionDto

class TestLatestFailedEventConsumptionDto(unittest.TestCase):
    """LatestFailedEventConsumptionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LatestFailedEventConsumptionDto:
        """Test LatestFailedEventConsumptionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LatestFailedEventConsumptionDto`
        """
        model = LatestFailedEventConsumptionDto()
        if include_optional:
            return LatestFailedEventConsumptionDto(
                consumed_by = '',
                consumed_time = '',
                error_reason = ''
            )
        else:
            return LatestFailedEventConsumptionDto(
        )
        """

    def testLatestFailedEventConsumptionDto(self):
        """Test LatestFailedEventConsumptionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
