# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.api.event_maestro_api import EventMaestroApi


class TestEventMaestroApi(unittest.IsolatedAsyncioTestCase):
    """EventMaestroApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EventMaestroApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_announce_event(self) -> None:
        """Test case for announce_event

        Announces an event for a case to maestro
        """
        pass

    async def test_consume_event(self) -> None:
        """Test case for consume_event

        Consumes an event for a case from the maestro
        """
        pass

    async def test_get_events_by_annotation(self) -> None:
        """Test case for get_events_by_annotation

        Retrieves events by annotation
        """
        pass

    async def test_reprocess_event(self) -> None:
        """Test case for reprocess_event

        Reprocesses an event from the maestro events log
        """
        pass

    async def test_reprocess_event_for_consumer(self) -> None:
        """Test case for reprocess_event_for_consumer

        Reprocesses an event for a specific consumer
        """
        pass


if __name__ == '__main__':
    unittest.main()
