# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.models.get_latest_events_details_response import GetLatestEventsDetailsResponse

class TestGetLatestEventsDetailsResponse(unittest.TestCase):
    """GetLatestEventsDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLatestEventsDetailsResponse:
        """Test GetLatestEventsDetailsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLatestEventsDetailsResponse`
        """
        model = GetLatestEventsDetailsResponse()
        if include_optional:
            return GetLatestEventsDetailsResponse(
                error_description = '',
                latest_events = [
                    leartech_maestro_service.models.latest_event_dto.LatestEventDto(
                        latest_failed_consumptions = [
                            leartech_maestro_service.models.latest_failed_event_consumption_dto.LatestFailedEventConsumptionDto(
                                consumed_by = '', 
                                consumed_time = '', 
                                error_reason = '', )
                            ], 
                        latest_successful_consumptions = [
                            leartech_maestro_service.models.latest_successful_event_consumption_dto.LatestSuccessfulEventConsumptionDto(
                                consumed_by = '', 
                                consumed_time = '', )
                            ], 
                        name = '', 
                        produced_by = '', 
                        produced_time = '', )
                    ],
                success = True
            )
        else:
            return GetLatestEventsDetailsResponse(
        )
        """

    def testGetLatestEventsDetailsResponse(self):
        """Test GetLatestEventsDetailsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
