# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.models.get_event_registration_info_for_name_response import GetEventRegistrationInfoForNameResponse

class TestGetEventRegistrationInfoForNameResponse(unittest.TestCase):
    """GetEventRegistrationInfoForNameResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEventRegistrationInfoForNameResponse:
        """Test GetEventRegistrationInfoForNameResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEventRegistrationInfoForNameResponse`
        """
        model = GetEventRegistrationInfoForNameResponse()
        if include_optional:
            return GetEventRegistrationInfoForNameResponse(
                error_description = '',
                event_registration = leartech_maestro_service.models.event_registration_info.EventRegistrationInfo(
                    consumers = [
                        leartech_maestro_service.models.consumer.Consumer(
                            service_name = '', 
                            url = '', )
                        ], 
                    name = '', 
                    producer = leartech_maestro_service.models.producer.Producer(
                        annotation_keys = [
                            ''
                            ], 
                        queue = '', 
                        service_name = '', ), ),
                success = True
            )
        else:
            return GetEventRegistrationInfoForNameResponse(
        )
        """

    def testGetEventRegistrationInfoForNameResponse(self):
        """Test GetEventRegistrationInfoForNameResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
