# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.models.latest_event_dto import LatestEventDto

class TestLatestEventDto(unittest.TestCase):
    """LatestEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LatestEventDto:
        """Test LatestEventDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LatestEventDto`
        """
        model = LatestEventDto()
        if include_optional:
            return LatestEventDto(
                latest_failed_consumptions = [
                    leartech_maestro_service.models.latest_failed_event_consumption_dto.LatestFailedEventConsumptionDto(
                        consumed_by = '', 
                        consumed_time = '', 
                        error_reason = '', )
                    ],
                latest_successful_consumptions = [
                    leartech_maestro_service.models.latest_successful_event_consumption_dto.LatestSuccessfulEventConsumptionDto(
                        consumed_by = '', 
                        consumed_time = '', )
                    ],
                name = '',
                produced_by = '',
                produced_time = ''
            )
        else:
            return LatestEventDto(
        )
        """

    def testLatestEventDto(self):
        """Test LatestEventDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
