# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.models.event_registration_info import EventRegistrationInfo

class TestEventRegistrationInfo(unittest.TestCase):
    """EventRegistrationInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventRegistrationInfo:
        """Test EventRegistrationInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventRegistrationInfo`
        """
        model = EventRegistrationInfo()
        if include_optional:
            return EventRegistrationInfo(
                consumers = [
                    leartech_maestro_service.models.consumer.Consumer(
                        service_name = '', 
                        url = '', )
                    ],
                name = '',
                producer = leartech_maestro_service.models.producer.Producer(
                    annotation_keys = [
                        ''
                        ], 
                    queue = '', 
                    service_name = '', )
            )
        else:
            return EventRegistrationInfo(
        )
        """

    def testEventRegistrationInfo(self):
        """Test EventRegistrationInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
