# coding: utf-8

"""
    Maestro Service API

    mini orchestration service for handling events

    The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_maestro_service.api.event_registration_api import EventRegistrationApi


class TestEventRegistrationApi(unittest.IsolatedAsyncioTestCase):
    """EventRegistrationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EventRegistrationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_event_registration_information(self) -> None:
        """Test case for get_event_registration_information

        Returns information about event registrations
        """
        pass

    async def test_get_event_registration_information_for_name(self) -> None:
        """Test case for get_event_registration_information_for_name

        Returns information about a given event registrations
        """
        pass


if __name__ == '__main__':
    unittest.main()
