# coding: utf-8

"""
    Leartech Go Service Template API

    Golden Go service template — replace this description after cloning.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_plan_api.models.handlers_example_response import HandlersExampleResponse

class TestHandlersExampleResponse(unittest.TestCase):
    """HandlersExampleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersExampleResponse:
        """Test HandlersExampleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersExampleResponse`
        """
        model = HandlersExampleResponse()
        if include_optional:
            return HandlersExampleResponse(
                message = 'hello',
                service = 'leartech-plan-api'
            )
        else:
            return HandlersExampleResponse(
        )
        """

    def testHandlersExampleResponse(self):
        """Test HandlersExampleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
