# coding: utf-8

# flake8: noqa
"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from leartech_auth_service.models.models_auth_response import ModelsAuthResponse
    from leartech_auth_service.models.models_login_request import ModelsLoginRequest
    from leartech_auth_service.models.models_two_factor_enable_response import ModelsTwoFactorEnableResponse
    from leartech_auth_service.models.models_two_factor_submit_request import ModelsTwoFactorSubmitRequest
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from leartech_auth_service.models.models_auth_response import ModelsAuthResponse
from leartech_auth_service.models.models_login_request import ModelsLoginRequest
from leartech_auth_service.models.models_two_factor_enable_response import ModelsTwoFactorEnableResponse
from leartech_auth_service.models.models_two_factor_submit_request import ModelsTwoFactorSubmitRequest

""",
            name=__name__,
            doc=__doc__,
        )
    )
