# coding: utf-8

# flake8: noqa
"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from leartech_ai_gateway.models.api_chat_completion_request import ApiChatCompletionRequest
    from leartech_ai_gateway.models.api_chat_completion_response import ApiChatCompletionResponse
    from leartech_ai_gateway.models.api_chat_message import ApiChatMessage
    from leartech_ai_gateway.models.api_choice import ApiChoice
    from leartech_ai_gateway.models.api_create_key_request import ApiCreateKeyRequest
    from leartech_ai_gateway.models.api_create_key_response import ApiCreateKeyResponse
    from leartech_ai_gateway.models.api_error import ApiError
    from leartech_ai_gateway.models.api_error_response import ApiErrorResponse
    from leartech_ai_gateway.models.api_key_view import ApiKeyView
    from leartech_ai_gateway.models.api_leartech_ext import ApiLeartechExt
    from leartech_ai_gateway.models.api_list_keys_response import ApiListKeysResponse
    from leartech_ai_gateway.models.api_model import ApiModel
    from leartech_ai_gateway.models.api_models_response import ApiModelsResponse
    from leartech_ai_gateway.models.api_request_message import ApiRequestMessage
    from leartech_ai_gateway.models.api_usage import ApiUsage
    from leartech_ai_gateway.models.api_usage_response import ApiUsageResponse
    from leartech_ai_gateway.models.store_usage_row import StoreUsageRow
    from leartech_ai_gateway.models.webfetch_result import WebfetchResult
    from leartech_ai_gateway.models.websearch_item import WebsearchItem
    from leartech_ai_gateway.models.websearch_results import WebsearchResults
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from leartech_ai_gateway.models.api_chat_completion_request import ApiChatCompletionRequest
from leartech_ai_gateway.models.api_chat_completion_response import ApiChatCompletionResponse
from leartech_ai_gateway.models.api_chat_message import ApiChatMessage
from leartech_ai_gateway.models.api_choice import ApiChoice
from leartech_ai_gateway.models.api_create_key_request import ApiCreateKeyRequest
from leartech_ai_gateway.models.api_create_key_response import ApiCreateKeyResponse
from leartech_ai_gateway.models.api_error import ApiError
from leartech_ai_gateway.models.api_error_response import ApiErrorResponse
from leartech_ai_gateway.models.api_key_view import ApiKeyView
from leartech_ai_gateway.models.api_leartech_ext import ApiLeartechExt
from leartech_ai_gateway.models.api_list_keys_response import ApiListKeysResponse
from leartech_ai_gateway.models.api_model import ApiModel
from leartech_ai_gateway.models.api_models_response import ApiModelsResponse
from leartech_ai_gateway.models.api_request_message import ApiRequestMessage
from leartech_ai_gateway.models.api_usage import ApiUsage
from leartech_ai_gateway.models.api_usage_response import ApiUsageResponse
from leartech_ai_gateway.models.store_usage_row import StoreUsageRow
from leartech_ai_gateway.models.webfetch_result import WebfetchResult
from leartech_ai_gateway.models.websearch_item import WebsearchItem
from leartech_ai_gateway.models.websearch_results import WebsearchResults

""",
            name=__name__,
            doc=__doc__,
        )
    )
