# coding: utf-8

"""
    leartech-ai-gateway

    OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiPricingModel(BaseModel):
    """
    ApiPricingModel
    """ # noqa: E501
    hosting: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    interface: Optional[StrictStr] = None
    provider: Optional[StrictStr] = None
    rates: Optional[Dict[str, StrictInt]] = Field(default=None, description="Rates is micros per 1000 tokens, keyed by kind (input, output, cache_read, cache_write_5m, cache_write_1h). A kind ABSENT from this map has no rate on file; it is not zero. The distinction is the point of the endpoint — see Unpriced.")
    unpriced: Optional[StrictBool] = Field(default=None, description="Unpriced reports that this model is callable and has NO input rate.  THIS IS THE FIELD THE ENDPOINT EXISTS FOR. A missing rate resolves to zero in the router's cost ranking, so an unpriced model reads as FREE and `auto` prefers it over every real supplier. Until now the only symptom was traffic silently moving. Reporting it as a boolean rather than as a zero in Rates keeps \"costs nothing\" and \"nobody set a price\" distinguishable, which is exactly the conflation that makes the defect invisible.  proven-by: TestPricing_AnUnpricedModelIsFlagged_NotReportedAsFree")
    __properties: ClassVar[List[str]] = ["hosting", "id", "interface", "provider", "rates", "unpriced"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiPricingModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiPricingModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "hosting": obj.get("hosting"),
            "id": obj.get("id"),
            "interface": obj.get("interface"),
            "provider": obj.get("provider"),
            "rates": obj.get("rates"),
            "unpriced": obj.get("unpriced")
        })
        return _obj


