# coding: utf-8

# flake8: noqa

"""
    Leartech Mortgages API

    Mortgages-domain BFF / orchestrator. REST + OpenAPI; sourcing comparison, indicative affordability, total-cost calculation, saved sourcing sessions, minimal case header. Consumed by leartech-mortgages-gw and any future SPA/mobile/partner client via auto-generated SDKs.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.2"

# Define package exports
__all__ = [
    "ExampleApi",
    "FleetTestApi",
    "HealthApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HandlersExampleResponse",
    "HandlersFleetTestResponse",
    "HandlersPeerResult",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from leartech_mortgages_api.api.example_api import ExampleApi as ExampleApi
    from leartech_mortgages_api.api.fleet_test_api import FleetTestApi as FleetTestApi
    from leartech_mortgages_api.api.health_api import HealthApi as HealthApi
    
    # import ApiClient
    from leartech_mortgages_api.api_response import ApiResponse as ApiResponse
    from leartech_mortgages_api.api_client import ApiClient as ApiClient
    from leartech_mortgages_api.configuration import Configuration as Configuration
    from leartech_mortgages_api.exceptions import OpenApiException as OpenApiException
    from leartech_mortgages_api.exceptions import ApiTypeError as ApiTypeError
    from leartech_mortgages_api.exceptions import ApiValueError as ApiValueError
    from leartech_mortgages_api.exceptions import ApiKeyError as ApiKeyError
    from leartech_mortgages_api.exceptions import ApiAttributeError as ApiAttributeError
    from leartech_mortgages_api.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from leartech_mortgages_api.models.handlers_example_response import HandlersExampleResponse as HandlersExampleResponse
    from leartech_mortgages_api.models.handlers_fleet_test_response import HandlersFleetTestResponse as HandlersFleetTestResponse
    from leartech_mortgages_api.models.handlers_peer_result import HandlersPeerResult as HandlersPeerResult
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from leartech_mortgages_api.api.example_api import ExampleApi as ExampleApi
from leartech_mortgages_api.api.fleet_test_api import FleetTestApi as FleetTestApi
from leartech_mortgages_api.api.health_api import HealthApi as HealthApi

# import ApiClient
from leartech_mortgages_api.api_response import ApiResponse as ApiResponse
from leartech_mortgages_api.api_client import ApiClient as ApiClient
from leartech_mortgages_api.configuration import Configuration as Configuration
from leartech_mortgages_api.exceptions import OpenApiException as OpenApiException
from leartech_mortgages_api.exceptions import ApiTypeError as ApiTypeError
from leartech_mortgages_api.exceptions import ApiValueError as ApiValueError
from leartech_mortgages_api.exceptions import ApiKeyError as ApiKeyError
from leartech_mortgages_api.exceptions import ApiAttributeError as ApiAttributeError
from leartech_mortgages_api.exceptions import ApiException as ApiException

# import models into sdk package
from leartech_mortgages_api.models.handlers_example_response import HandlersExampleResponse as HandlersExampleResponse
from leartech_mortgages_api.models.handlers_fleet_test_response import HandlersFleetTestResponse as HandlersFleetTestResponse
from leartech_mortgages_api.models.handlers_peer_result import HandlersPeerResult as HandlersPeerResult

""",
            name=__name__,
            doc=__doc__,
        )
    )
