# coding: utf-8

# flake8: noqa

"""
    Catalog MCP API

    Read-only inventory of leartech services for BA/Architect agents. Foundation for V6-P10 + the new-product layer.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.2"

# Define package exports
__all__ = [
    "ExampleApi",
    "HealthApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HandlersExampleResponse",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from leartech_catalog_mcp.api.example_api import ExampleApi as ExampleApi
    from leartech_catalog_mcp.api.health_api import HealthApi as HealthApi
    
    # import ApiClient
    from leartech_catalog_mcp.api_response import ApiResponse as ApiResponse
    from leartech_catalog_mcp.api_client import ApiClient as ApiClient
    from leartech_catalog_mcp.configuration import Configuration as Configuration
    from leartech_catalog_mcp.exceptions import OpenApiException as OpenApiException
    from leartech_catalog_mcp.exceptions import ApiTypeError as ApiTypeError
    from leartech_catalog_mcp.exceptions import ApiValueError as ApiValueError
    from leartech_catalog_mcp.exceptions import ApiKeyError as ApiKeyError
    from leartech_catalog_mcp.exceptions import ApiAttributeError as ApiAttributeError
    from leartech_catalog_mcp.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from leartech_catalog_mcp.models.handlers_example_response import HandlersExampleResponse as HandlersExampleResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from leartech_catalog_mcp.api.example_api import ExampleApi as ExampleApi
from leartech_catalog_mcp.api.health_api import HealthApi as HealthApi

# import ApiClient
from leartech_catalog_mcp.api_response import ApiResponse as ApiResponse
from leartech_catalog_mcp.api_client import ApiClient as ApiClient
from leartech_catalog_mcp.configuration import Configuration as Configuration
from leartech_catalog_mcp.exceptions import OpenApiException as OpenApiException
from leartech_catalog_mcp.exceptions import ApiTypeError as ApiTypeError
from leartech_catalog_mcp.exceptions import ApiValueError as ApiValueError
from leartech_catalog_mcp.exceptions import ApiKeyError as ApiKeyError
from leartech_catalog_mcp.exceptions import ApiAttributeError as ApiAttributeError
from leartech_catalog_mcp.exceptions import ApiException as ApiException

# import models into sdk package
from leartech_catalog_mcp.models.handlers_example_response import HandlersExampleResponse as HandlersExampleResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
