# coding: utf-8

# flake8: noqa

"""
    leartech-rust-service-template

    Golden Rust HTTP service starter for leartech.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.0.5"

# Define package exports
__all__ = [
    "ExampleApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ExampleResponse",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from leartech_rust_service_template.api.example_api import ExampleApi as ExampleApi
    
    # import ApiClient
    from leartech_rust_service_template.api_response import ApiResponse as ApiResponse
    from leartech_rust_service_template.api_client import ApiClient as ApiClient
    from leartech_rust_service_template.configuration import Configuration as Configuration
    from leartech_rust_service_template.exceptions import OpenApiException as OpenApiException
    from leartech_rust_service_template.exceptions import ApiTypeError as ApiTypeError
    from leartech_rust_service_template.exceptions import ApiValueError as ApiValueError
    from leartech_rust_service_template.exceptions import ApiKeyError as ApiKeyError
    from leartech_rust_service_template.exceptions import ApiAttributeError as ApiAttributeError
    from leartech_rust_service_template.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from leartech_rust_service_template.models.example_response import ExampleResponse as ExampleResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from leartech_rust_service_template.api.example_api import ExampleApi as ExampleApi

# import ApiClient
from leartech_rust_service_template.api_response import ApiResponse as ApiResponse
from leartech_rust_service_template.api_client import ApiClient as ApiClient
from leartech_rust_service_template.configuration import Configuration as Configuration
from leartech_rust_service_template.exceptions import OpenApiException as OpenApiException
from leartech_rust_service_template.exceptions import ApiTypeError as ApiTypeError
from leartech_rust_service_template.exceptions import ApiValueError as ApiValueError
from leartech_rust_service_template.exceptions import ApiKeyError as ApiKeyError
from leartech_rust_service_template.exceptions import ApiAttributeError as ApiAttributeError
from leartech_rust_service_template.exceptions import ApiException as ApiException

# import models into sdk package
from leartech_rust_service_template.models.example_response import ExampleResponse as ExampleResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
