# coding: utf-8

"""
    Catalog MCP API

    Read-only inventory of leartech services for BA/Architect agents. Foundation for V6-P10 + the new-product layer.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_catalog_mcp.models.handlers_fleet_test_response import HandlersFleetTestResponse

class TestHandlersFleetTestResponse(unittest.TestCase):
    """HandlersFleetTestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlersFleetTestResponse:
        """Test HandlersFleetTestResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlersFleetTestResponse`
        """
        model = HandlersFleetTestResponse()
        if include_optional:
            return HandlersFleetTestResponse(
                results = [
                    leartech_catalog_mcp.models.handlers/peer_result.handlers.peerResult(
                        duration_ms = 56, 
                        http_code = 56, 
                        message = '', 
                        ok = True, 
                        peer = '', )
                    ],
                success = True,
                summary = ''
            )
        else:
            return HandlersFleetTestResponse(
        )
        """

    def testHandlersFleetTestResponse(self):
        """Test HandlersFleetTestResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
