# coding: utf-8

"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_auth_service.api.two_factor_api import TwoFactorApi


class TestTwoFactorApi(unittest.IsolatedAsyncioTestCase):
    """TwoFactorApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TwoFactorApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_disable_two_factor(self) -> None:
        """Test case for disable_two_factor

        Disable 2FA
        """
        pass

    async def test_enable_two_factor(self) -> None:
        """Test case for enable_two_factor

        Start 2FA setup
        """
        pass

    async def test_submit_two_factor(self) -> None:
        """Test case for submit_two_factor

        Submit 2FA code during login
        """
        pass

    async def test_verify_two_factor(self) -> None:
        """Test case for verify_two_factor

        Verify 2FA setup
        """
        pass


if __name__ == '__main__':
    unittest.main()
