# coding: utf-8

"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_auth_service.models.models_user import ModelsUser

class TestModelsUser(unittest.TestCase):
    """ModelsUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsUser:
        """Test ModelsUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsUser`
        """
        model = ModelsUser()
        if include_optional:
            return ModelsUser(
                active = True,
                created_at = '',
                display_name = '',
                email = '',
                id = '',
                permissions = [
                    ''
                    ],
                role = '',
                tenant_id = '',
                updated_at = ''
            )
        else:
            return ModelsUser(
        )
        """

    def testModelsUser(self):
        """Test ModelsUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
