# coding: utf-8

"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_auth_service.models.models_two_factor_submit_request import ModelsTwoFactorSubmitRequest

class TestModelsTwoFactorSubmitRequest(unittest.TestCase):
    """ModelsTwoFactorSubmitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsTwoFactorSubmitRequest:
        """Test ModelsTwoFactorSubmitRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsTwoFactorSubmitRequest`
        """
        model = ModelsTwoFactorSubmitRequest()
        if include_optional:
            return ModelsTwoFactorSubmitRequest(
                code = ''
            )
        else:
            return ModelsTwoFactorSubmitRequest(
                code = '',
        )
        """

    def testModelsTwoFactorSubmitRequest(self):
        """Test ModelsTwoFactorSubmitRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
