# coding: utf-8

"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_auth_service.models.models_dcr_register_request import ModelsDCRRegisterRequest

class TestModelsDCRRegisterRequest(unittest.TestCase):
    """ModelsDCRRegisterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelsDCRRegisterRequest:
        """Test ModelsDCRRegisterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelsDCRRegisterRequest`
        """
        model = ModelsDCRRegisterRequest()
        if include_optional:
            return ModelsDCRRegisterRequest(
                client_name = '',
                contacts = [
                    ''
                    ],
                grant_types = [
                    ''
                    ],
                redirect_uris = [
                    ''
                    ],
                response_types = [
                    ''
                    ],
                scope = '',
                software_id = '',
                software_version = '',
                token_endpoint_auth_method = ''
            )
        else:
            return ModelsDCRRegisterRequest(
        )
        """

    def testModelsDCRRegisterRequest(self):
        """Test ModelsDCRRegisterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
