# coding: utf-8

"""
    Leartech Auth Service API

    Authentication service providing Hydra login/consent flow, 2FA (TOTP), and user management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from leartech_auth_service.api.login_api import LoginApi


class TestLoginApi(unittest.IsolatedAsyncioTestCase):
    """LoginApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LoginApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_consent(self) -> None:
        """Test case for get_consent

        Process OAuth2 consent
        """
        pass

    async def test_get_login(self) -> None:
        """Test case for get_login

        Get login challenge from Hydra
        """
        pass

    async def test_get_logout(self) -> None:
        """Test case for get_logout

        Handle Hydra logout callback
        """
        pass

    async def test_post_login(self) -> None:
        """Test case for post_login

        Submit login credentials
        """
        pass


if __name__ == '__main__':
    unittest.main()
